config/routes.rb
Oats::Application.routes.draw do
  resources :employees
  resources :companies
  resources :worktimes
  resources :session_employees, only: [:new, :create, :destroy]
  resources :session_companies, only: [:new, :create, :destroy]
  resources :offices, only: [:create, :destroy, :update]
  match '/company/signup',  to: 'companies#new'
  match '/company/signin',  to: 'session_companies#new'
  match '/company/signout',  to: 'session_companies#destroy', via: :delete
  match '/company/new_employee', to: 'companies#new_employee'
  match '/company/edit_employee/:id', to: 'companies#edit_employee'

  match '/employee/signup', to: 'employees#new'
  match '/employee/signin',  to: 'session_employees#new'
  match '/employee/signout', to: 'session_employees#destroy', via: :delete
  match '/employee/edit_employee/:id', to: 'employees#edit_employee'
  match '/employee/reset_pass/:id', to: 'employees#reset_pass'
  match '/employee/performance/:id', to: 'employees#performance'
  match '/employee/checkin', to: 'worktimes#create', via: :post
  match '/employee/checkout', to: 'worktimes#update', via: :post

  match '/home',  to: 'static_pages#home'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/terms', to: 'static_pages#terms'
  match '/privacy', to: 'static_pages#privacy'
  match '/clientsandtestimony', to: 'static_pages#clientsandtestimony'
  match '/help', to: 'static_pages#help'

end

app/controllers/session_companies_controller.rb
class SessionCompaniesController < ApplicationController
  def new
  end

  def create
    company = Company.find_by_username(params[:session][:username].downcase)
    if company && company.authenticate(params[:session][:password])
      company_sign_in company
      redirect_back_or company
    else
      render 'new'
    end
  end

  def destroy
    company_sign_out
    redirect_to '/company/signin'
  end
end

app/views/session_companies/new.html.erb
<% provide(:title, 'Company Sign in') %>
<% provide(:description, 'none') %>
<div>
  <h1>Company Sign in</h1>
</div>
<div class="login_form">
  <%= form_for(:session, url: session_companies_path) do |f| %>

    <%= f.label :username %>
    <%= f.text_field :username %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.submit "Sign in", class: "orange_button login_button" %>
  <% end %>

  <p>New user? <%= link_to "Sign up now!", '/company/signup' %></p>
</div>